-- Host KYC QR Module
-- Implements host-centric QR generation, regen requests, and traveller KYC submissions

-- ─────────────────────────────────────────────
-- Table: host_qr_codes
-- One active QR per host, generated by the host themselves
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.host_qr_codes (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id       UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token         TEXT        NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(24), 'hex'),
  qr_status     TEXT        NOT NULL DEFAULT 'active'
                              CHECK (qr_status IN ('active', 'revoked', 'inactive')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  regenerated_at TIMESTAMPTZ,
  is_active     BOOLEAN     NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_host_qr_codes_host_id ON public.host_qr_codes(host_id);
CREATE INDEX IF NOT EXISTS idx_host_qr_codes_token   ON public.host_qr_codes(token);

ALTER TABLE public.host_qr_codes ENABLE ROW LEVEL SECURITY;

-- Host sees own QR codes
DROP POLICY IF EXISTS "host_qr_own_select" ON public.host_qr_codes;
CREATE POLICY "host_qr_own_select" ON public.host_qr_codes
  FOR SELECT TO authenticated
  USING (host_id = auth.uid());

-- Admin sees all
DROP POLICY IF EXISTS "host_qr_admin_all" ON public.host_qr_codes;
CREATE POLICY "host_qr_admin_all" ON public.host_qr_codes
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Anonymous (QR scan page) can read token for validation only
DROP POLICY IF EXISTS "host_qr_anon_select" ON public.host_qr_codes;
CREATE POLICY "host_qr_anon_select" ON public.host_qr_codes
  FOR SELECT TO anon
  USING (true);

-- ─────────────────────────────────────────────
-- Table: qr_regen_requests
-- Host requests to regenerate QR; needs admin approval
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.qr_regen_requests (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  host_id          UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  request_type     TEXT        NOT NULL DEFAULT 'regenerate',
  status           TEXT        NOT NULL DEFAULT 'pending'
                                 CHECK (status IN ('pending', 'approved', 'rejected')),
  requested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_by      UUID        REFERENCES public.profiles(id),
  approved_at      TIMESTAMPTZ,
  rejection_reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_qr_regen_host   ON public.qr_regen_requests(host_id);
CREATE INDEX IF NOT EXISTS idx_qr_regen_status ON public.qr_regen_requests(status);

ALTER TABLE public.qr_regen_requests ENABLE ROW LEVEL SECURITY;

-- Host sees own requests
DROP POLICY IF EXISTS "qr_regen_host_select" ON public.qr_regen_requests;
CREATE POLICY "qr_regen_host_select" ON public.qr_regen_requests
  FOR SELECT TO authenticated
  USING (host_id = auth.uid());

-- Host inserts own request (one pending at a time enforced via function)
DROP POLICY IF EXISTS "qr_regen_host_insert" ON public.qr_regen_requests;
CREATE POLICY "qr_regen_host_insert" ON public.qr_regen_requests
  FOR INSERT TO authenticated
  WITH CHECK (host_id = auth.uid() AND public.has_role(auth.uid(), 'host'));

-- Admin sees all and can update
DROP POLICY IF EXISTS "qr_regen_admin_all" ON public.qr_regen_requests;
CREATE POLICY "qr_regen_admin_all" ON public.qr_regen_requests
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- ─────────────────────────────────────────────
-- Table: traveller_kyc
-- KYC submissions by travellers who scan a host's QR code
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.traveller_kyc (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  traveller_id        UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  host_id             UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  qr_id               UUID        NOT NULL REFERENCES public.host_qr_codes(id) ON DELETE CASCADE,
  full_name           TEXT        NOT NULL,
  mobile              TEXT        NOT NULL,
  email               TEXT,
  address             TEXT,
  aadhaar             TEXT,
  pan                 TEXT,
  driving_licence     TEXT,
  emergency_contact   JSONB       NOT NULL DEFAULT '{}',
  uploaded_documents  JSONB       NOT NULL DEFAULT '[]',
  verification_status TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_traveller_kyc_host_id ON public.traveller_kyc(host_id);
CREATE INDEX IF NOT EXISTS idx_traveller_kyc_qr_id   ON public.traveller_kyc(qr_id);
CREATE INDEX IF NOT EXISTS idx_traveller_kyc_created ON public.traveller_kyc(created_at DESC);

ALTER TABLE public.traveller_kyc ENABLE ROW LEVEL SECURITY;

-- Traveller sees own submission
DROP POLICY IF EXISTS "traveller_kyc_own_select" ON public.traveller_kyc;
CREATE POLICY "traveller_kyc_own_select" ON public.traveller_kyc
  FOR SELECT TO authenticated
  USING (traveller_id = auth.uid());

-- Host sees submissions for their QR (raw row access; masking done via RPC)
DROP POLICY IF EXISTS "traveller_kyc_host_select" ON public.traveller_kyc;
CREATE POLICY "traveller_kyc_host_select" ON public.traveller_kyc
  FOR SELECT TO authenticated
  USING (host_id = auth.uid() AND public.has_role(auth.uid(), 'host'));

-- Admin full access
DROP POLICY IF EXISTS "traveller_kyc_admin_all" ON public.traveller_kyc;
CREATE POLICY "traveller_kyc_admin_all" ON public.traveller_kyc
  FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Public insert (unauthenticated traveller submits KYC via QR link)
DROP POLICY IF EXISTS "traveller_kyc_public_insert" ON public.traveller_kyc;
CREATE POLICY "traveller_kyc_public_insert" ON public.traveller_kyc
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- ─────────────────────────────────────────────
-- RPC: generate_host_qr()
-- Host generates their first QR; fails if one already exists
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.generate_host_qr()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_host_id UUID := auth.uid();
  v_token   TEXT;
  v_qr_id   UUID;
  v_count   INT;
BEGIN
  IF NOT public.has_role(v_host_id, 'host') THEN
    RAISE EXCEPTION 'Only hosts can generate QR codes';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM public.host_qr_codes
  WHERE host_id = v_host_id;

  IF v_count > 0 THEN
    RAISE EXCEPTION 'QR code already exists. Submit a regeneration request for a new one.';
  END IF;

  v_token := encode(gen_random_bytes(24), 'hex');

  INSERT INTO public.host_qr_codes (host_id, token, qr_status, is_active)
  VALUES (v_host_id, v_token, 'active', true)
  RETURNING id INTO v_qr_id;

  -- Notify host
  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_host_id, 'QR Code Generated', 'Your KYC QR code has been generated and is ready to use.', 'system');

  RETURN jsonb_build_object('id', v_qr_id, 'token', v_token, 'created_at', NOW());
END;
$$;

REVOKE ALL ON FUNCTION public.generate_host_qr() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.generate_host_qr() TO authenticated;

-- ─────────────────────────────────────────────
-- RPC: request_qr_regen()
-- Host submits a regeneration request; blocked if one is already pending
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.request_qr_regen()
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_host_id   UUID := auth.uid();
  v_req_id    UUID;
  v_pending   INT;
BEGIN
  IF NOT public.has_role(v_host_id, 'host') THEN
    RAISE EXCEPTION 'Only hosts can request QR regeneration';
  END IF;

  SELECT COUNT(*) INTO v_pending
  FROM public.qr_regen_requests
  WHERE host_id = v_host_id AND status = 'pending';

  IF v_pending > 0 THEN
    RAISE EXCEPTION 'A regeneration request is already pending approval.';
  END IF;

  INSERT INTO public.qr_regen_requests (host_id, request_type, status)
  VALUES (v_host_id, 'regenerate', 'pending')
  RETURNING id INTO v_req_id;

  -- Notify admins (insert for any user with admin role)
  INSERT INTO public.notifications (user_id, title, message, type)
  SELECT p.id,
    'QR Regen Request',
    'A host has requested QR code regeneration and requires your approval.',
    'system'
  FROM public.profiles p
  JOIN public.user_roles ur ON ur.user_id = p.id
  WHERE ur.role = 'admin';

  RETURN v_req_id;
END;
$$;

REVOKE ALL ON FUNCTION public.request_qr_regen() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.request_qr_regen() TO authenticated;

-- ─────────────────────────────────────────────
-- RPC: approve_qr_regen(p_request_id)
-- Admin approves regen: revokes old QR, generates new one, notifies host
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.approve_qr_regen(p_request_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_host_id   UUID;
  v_new_token TEXT;
  v_new_qr_id UUID;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Only admins can approve QR regeneration';
  END IF;

  SELECT host_id INTO v_host_id
  FROM public.qr_regen_requests
  WHERE id = p_request_id AND status = 'pending';

  IF v_host_id IS NULL THEN
    RAISE EXCEPTION 'Request not found or already resolved';
  END IF;

  -- Revoke all active QR codes for this host
  UPDATE public.host_qr_codes
  SET qr_status = 'revoked', is_active = false
  WHERE host_id = v_host_id AND is_active = true;

  -- Generate fresh QR
  v_new_token := encode(gen_random_bytes(24), 'hex');
  INSERT INTO public.host_qr_codes (host_id, token, qr_status, is_active, regenerated_at)
  VALUES (v_host_id, v_new_token, 'active', true, NOW())
  RETURNING id INTO v_new_qr_id;

  -- Mark request approved
  UPDATE public.qr_regen_requests
  SET status = 'approved', approved_by = auth.uid(), approved_at = NOW()
  WHERE id = p_request_id;

  -- Notify host
  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (v_host_id, 'QR Code Approved', 'Your QR code regeneration request has been approved. A new QR code is now active.', 'system');

  RETURN jsonb_build_object('id', v_new_qr_id, 'token', v_new_token);
END;
$$;

REVOKE ALL ON FUNCTION public.approve_qr_regen(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.approve_qr_regen(UUID) TO authenticated;

-- ─────────────────────────────────────────────
-- RPC: reject_qr_regen(p_request_id, p_reason)
-- Admin rejects regen; old QR stays revoked
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.reject_qr_regen(p_request_id UUID, p_reason TEXT DEFAULT NULL)
RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_host_id UUID;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Only admins can reject QR regeneration';
  END IF;

  SELECT host_id INTO v_host_id
  FROM public.qr_regen_requests
  WHERE id = p_request_id AND status = 'pending';

  IF v_host_id IS NULL THEN
    RAISE EXCEPTION 'Request not found or already resolved';
  END IF;

  UPDATE public.qr_regen_requests
  SET status = 'rejected',
      approved_by = auth.uid(),
      approved_at = NOW(),
      rejection_reason = p_reason
  WHERE id = p_request_id;

  INSERT INTO public.notifications (user_id, title, message, type)
  VALUES (
    v_host_id,
    'QR Code Request Rejected',
    COALESCE('Your QR code regeneration request was rejected. Reason: ' || p_reason, 'Your QR code regeneration request was rejected.'),
    'system'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.reject_qr_regen(UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reject_qr_regen(UUID, TEXT) TO authenticated;

-- ─────────────────────────────────────────────
-- RPC: get_host_traveller_kyc(p_host_id)
-- Returns masked data for hosts; full data for admins
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_host_traveller_kyc(p_host_id UUID DEFAULT NULL)
RETURNS TABLE (
  id                  UUID,
  host_id             UUID,
  full_name           TEXT,
  mobile              TEXT,
  email               TEXT,
  aadhaar             TEXT,
  pan                 TEXT,
  driving_licence     TEXT,
  emergency_contact   JSONB,
  verification_status TEXT,
  created_at          TIMESTAMPTZ
) LANGUAGE plpgsql SECURITY DEFINER STABLE AS $$
BEGIN
  IF public.has_role(auth.uid(), 'admin') THEN
    RETURN QUERY
      SELECT kyc.id, kyc.host_id, kyc.full_name, kyc.mobile, kyc.email,
             kyc.aadhaar, kyc.pan, kyc.driving_licence,
             kyc.emergency_contact, kyc.verification_status, kyc.created_at
      FROM public.traveller_kyc kyc
      WHERE (p_host_id IS NULL OR kyc.host_id = p_host_id)
      ORDER BY kyc.created_at DESC;
  ELSIF public.has_role(auth.uid(), 'host') THEN
    RETURN QUERY
      SELECT
        kyc.id,
        kyc.host_id,
        kyc.full_name,
        -- Mask mobile: keep last 4
        'XXXXXXXX' || RIGHT(kyc.mobile, 4)                                       AS mobile,
        kyc.email,
        -- Mask aadhaar
        CASE WHEN kyc.aadhaar IS NOT NULL AND length(kyc.aadhaar) >= 4
             THEN 'XXXX XXXX ' || RIGHT(regexp_replace(kyc.aadhaar, '\s', '', 'g'), 4)
             ELSE kyc.aadhaar END                                                 AS aadhaar,
        -- Mask PAN
        CASE WHEN kyc.pan IS NOT NULL AND length(kyc.pan) >= 4
             THEN 'XXXXXX' || RIGHT(kyc.pan, 4)
             ELSE kyc.pan END                                                     AS pan,
        -- Mask Driving Licence
        CASE WHEN kyc.driving_licence IS NOT NULL AND length(kyc.driving_licence) >= 4
             THEN 'XXXXXXXX' || RIGHT(kyc.driving_licence, 4)
             ELSE kyc.driving_licence END                                         AS driving_licence,
        kyc.emergency_contact,
        kyc.verification_status,
        kyc.created_at
      FROM public.traveller_kyc kyc
      WHERE kyc.host_id = auth.uid()
      ORDER BY kyc.created_at DESC;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.get_host_traveller_kyc(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_host_traveller_kyc(UUID) TO authenticated;

-- ─────────────────────────────────────────────
-- RPC: admin_update_traveller_kyc_status
-- Admin updates verification status for a traveller KYC record
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admin_update_traveller_kyc_status(
  p_kyc_id UUID,
  p_status TEXT
) RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF p_status NOT IN ('pending', 'verified', 'rejected') THEN
    RAISE EXCEPTION 'Invalid status';
  END IF;
  UPDATE public.traveller_kyc
  SET verification_status = p_status
  WHERE id = p_kyc_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_update_traveller_kyc_status(UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_update_traveller_kyc_status(UUID, TEXT) TO authenticated;

-- ─────────────────────────────────────────────
-- Explicit table grants (ensures anon/authenticated can access regardless of
-- Supabase default privilege setup — RLS still enforces row-level restrictions)
-- ─────────────────────────────────────────────
GRANT SELECT ON public.host_qr_codes    TO anon, authenticated;
GRANT SELECT, INSERT ON public.traveller_kyc   TO anon, authenticated;
GRANT SELECT, INSERT ON public.qr_regen_requests TO authenticated;
