-- KYC QR Codes: per-traveller QR tokens for secure KYC form submission
-- Generated by host; re-generation requires Super Admin approval.

CREATE TABLE IF NOT EXISTS kyc_qr_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'expired')),
  generated_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT NOW() + INTERVAL '30 days'
);

CREATE INDEX IF NOT EXISTS idx_kyc_qr_user ON kyc_qr_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_kyc_qr_token ON kyc_qr_codes(token);

ALTER TABLE kyc_qr_codes ENABLE ROW LEVEL SECURITY;

-- Hosts can view QR codes for travellers they manage (via hub)
DROP POLICY IF EXISTS "Hosts can view traveller QR codes" ON kyc_qr_codes;
CREATE POLICY "Hosts can view traveller QR codes" ON kyc_qr_codes FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('host', 'admin'))
);

-- Only admins can insert/update (hosts request via kyc_qr_requests table)
DROP POLICY IF EXISTS "Admins manage QR codes" ON kyc_qr_codes;
CREATE POLICY "Admins manage QR codes" ON kyc_qr_codes FOR ALL TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- Anyone can read their own QR code (travellers)
DROP POLICY IF EXISTS "Users view own QR code" ON kyc_qr_codes;
CREATE POLICY "Users view own QR code" ON kyc_qr_codes FOR SELECT TO authenticated USING (user_id = auth.uid());

-- Anonymous read for QR page (token-gated, no auth required to submit KYC)
DROP POLICY IF EXISTS "Public read by token" ON kyc_qr_codes;
CREATE POLICY "Public read by token" ON kyc_qr_codes FOR SELECT TO anon USING (true);

-- KYC QR regeneration requests (host → admin approval)
CREATE TABLE IF NOT EXISTS kyc_qr_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  traveller_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  requested_by UUID NOT NULL REFERENCES auth.users(id),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

ALTER TABLE kyc_qr_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hosts manage own requests" ON kyc_qr_requests;
CREATE POLICY "Hosts manage own requests" ON kyc_qr_requests FOR ALL TO authenticated USING (
  requested_by = auth.uid() OR
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- KYC submissions via QR form
CREATE TABLE IF NOT EXISTS kyc_qr_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qr_token TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  government_id_type TEXT,
  government_id_number TEXT,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  emergency_contact_relation TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'reviewed', 'approved', 'rejected'))
);

ALTER TABLE kyc_qr_submissions ENABLE ROW LEVEL SECURITY;

-- Admins can see everything; anon can insert (public KYC form)
DROP POLICY IF EXISTS "Admin views all submissions" ON kyc_qr_submissions;
CREATE POLICY "Admin views all submissions" ON kyc_qr_submissions FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

DROP POLICY IF EXISTS "Public KYC submission" ON kyc_qr_submissions;
CREATE POLICY "Public KYC submission" ON kyc_qr_submissions FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Hosts view submissions for their travellers (masked — only through a view)
DROP POLICY IF EXISTS "Hosts view submissions" ON kyc_qr_submissions;
CREATE POLICY "Hosts view submissions" ON kyc_qr_submissions FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('host', 'admin'))
);

-- Function: host generates first QR for a traveller
CREATE OR REPLACE FUNCTION generate_traveller_qr(p_traveller_id UUID, p_host_id UUID)
RETURNS TEXT AS $$
DECLARE
  v_token TEXT;
  v_existing_count INT;
BEGIN
  -- Only first QR allowed via this function; subsequent need admin approval
  SELECT COUNT(*) INTO v_existing_count FROM kyc_qr_codes WHERE user_id = p_traveller_id;
  IF v_existing_count > 0 THEN
    RAISE EXCEPTION 'QR already exists. Request a new one via admin approval.';
  END IF;

  -- Verify caller is a host or admin
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = p_host_id AND role IN ('host', 'admin')) THEN
    RAISE EXCEPTION 'Only hosts or admins may generate QR codes';
  END IF;

  v_token := encode(gen_random_bytes(24), 'hex');

  INSERT INTO kyc_qr_codes (user_id, token, status, generated_by)
  VALUES (p_traveller_id, v_token, 'active', p_host_id);

  RETURN v_token;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

REVOKE ALL ON FUNCTION generate_traveller_qr(UUID, UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION generate_traveller_qr(UUID, UUID) TO authenticated;
