// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = "https://uhtwkajqpuazxpnbaojx.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVodHdrYWpxcHVhenhwbmJhb2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzY1NTcsImV4cCI6MjA3NzI1MjU1N30.RPdeJk13uqnFssQXUyA0acsf53xgceR-59VLzoB7Wfg";

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim() || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "").trim() || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

/** False when URL/key missing — UI should gate before relying on Supabase. */
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const resolvedUrl = isSupabaseConfigured ? SUPABASE_URL : "https://configuration-required.supabase.co";
const resolvedKey = isSupabaseConfigured
  ? SUPABASE_PUBLISHABLE_KEY
  : "sb-publishable-api-key-not-configured";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const customStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined' && window.localStorage.getItem('remember_me') === 'false') {
      return window.sessionStorage.getItem(key);
    }
    return typeof window !== 'undefined' ? window.localStorage.getItem(key) : null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined') {
      if (window.localStorage.getItem('remember_me') === 'false') {
        window.sessionStorage.setItem(key, value);
      } else {
        window.localStorage.setItem(key, value);
      }
    }
  },
  removeItem: (key: string) => {
    if (typeof window !== 'undefined') {
      window.localStorage.removeItem(key);
      window.sessionStorage.removeItem(key);
    }
  }
};

export const supabase = createClient<Database>(resolvedUrl, resolvedKey, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});